/**
 * Xero, over `fetch`, with no package.
 *
 * The rule this file exists to keep: **no `xero` npm package.** Tickmark's whole pitch is that an
 * operator can read what they are running, and the official SDK is a dependency tree in a project with
 * none. The OAuth 2.0 flow and the REST calls are a handful of `fetch`es and a JSON transform, and
 * those lines are auditable in one sitting — the same bargain `stripe.js` makes beside it.
 *
 * ## What is here
 *
 * - `authorizationUrl` — the redirect that starts the OAuth dance, carrying a `state` the callback must
 *   hand back. That `state` is the CSRF guard: a forged callback cannot land without it.
 * - `exchangeCode` / `refreshTokens` — the token lifecycle against `identity.xero.com/connect/token`.
 * - `fetchConnections` — the practice's client list: every Xero organisation they manage, which is the
 *   book of clients a practice keeps *in* Xero (one organisation is one client they act for).
 * - `connectionsToRows` — the transform into `{ name, email }` rows, so a Xero import pours into the
 *   same ingestion pipeline a CSV does, with the same dry run and the same report.
 *
 * ## What is deliberately not here
 *
 * No retries, and no attempt to model Xero's object graph. Each call reads the two or three fields it
 * needs and ignores the rest, which is what keeps this file small enough to read in full. The richer
 * client record — a name *and* a contact address — lives in Xero Practice Manager's Clients rather
 * than in `connections`; `connectionsToRows` is the seam that source is aimed at when a practice needs
 * it, so both pour into one pipeline.
 */

export const XERO_AUTHORIZE_URL = 'https://login.xero.com/identity/connect/authorize';
export const XERO_TOKEN_URL = 'https://identity.xero.com/connect/token';
export const XERO_CONNECTIONS_URL = 'https://api.xero.com/connections';

/**
 * What an import asks for. Identity plus `offline_access` (so there is a refresh token and the import
 * is not a one-shot), and a *read* of the accounting data that names the organisations. Narrow on
 * purpose: a client-list import has no business asking to write to anybody's books.
 */
export const XERO_SCOPES = [
  'openid',
  'email',
  'profile',
  'offline_access',
  'accounting.contacts',
  'accounting.settings',
].join(' ');

export class XeroError extends Error {
  constructor(message, { status = null, raw = null } = {}) {
    super(message);
    this.name = 'XeroError';
    this.status = status;
    this.raw = raw;
  }
}

/** Configuration from the environment, or null when the Xero integration is not set up. */
export function xeroFromEnvironment(env = process.env) {
  const clientId = env.TICKMARK_XERO_CLIENT_ID;
  const clientSecret = env.TICKMARK_XERO_CLIENT_SECRET;
  if (!clientId || !clientSecret) return null;
  const base = (env.TICKMARK_PUBLIC_URL ?? 'http://localhost:3000').replace(/\/+$/, '');
  return {
    clientId,
    clientSecret,
    // Where Xero sends the browser back to. Derived from one base URL so the return path cannot drift
    // from the rest of the app, but overridable — a reverse proxy may front this at its own address.
    redirectUri: env.TICKMARK_XERO_REDIRECT_URI ?? `${base}/integrations/xero/callback`,
  };
}

/**
 * The redirect that starts the OAuth dance.
 *
 * `state` is generated by the caller and stashed somewhere the callback can compare against; it is not
 * a nicety here but the one thing that makes an unsolicited `/callback` harmless.
 */
export function authorizationUrl({ config, state, scopes = XERO_SCOPES }) {
  const url = new URL(XERO_AUTHORIZE_URL);
  url.searchParams.set('response_type', 'code');
  url.searchParams.set('client_id', config.clientId);
  url.searchParams.set('redirect_uri', config.redirectUri);
  url.searchParams.set('scope', scopes);
  url.searchParams.set('state', state);
  return url.toString();
}

/** POST to the token endpoint and hand back the JSON, or throw this module's own words. */
async function tokenRequest(config, body) {
  // Xero authenticates the token call with HTTP Basic — client id and secret, not a bearer — because
  // this is the one leg where the secret is the proof, before there is a bearer to send.
  const credentials = Buffer.from(`${config.clientId}:${config.clientSecret}`).toString('base64');
  const response = await fetch(XERO_TOKEN_URL, {
    method: 'POST',
    headers: {
      authorization: `Basic ${credentials}`,
      'content-type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams(body).toString(),
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new XeroError(
      payload?.error_description ?? payload?.error ?? `Xero refused the token request (${response.status})`,
      { status: response.status, raw: payload },
    );
  }
  return payload;
}

/** Shape Xero's token response into one vocabulary, so callers never see `expires_in` vs `access_token`. */
function readTokens(payload) {
  return {
    accessToken: payload.access_token,
    refreshToken: payload.refresh_token,
    expiresIn: Number(payload.expires_in ?? 0),
    tokenType: payload.token_type ?? 'Bearer',
    scope: payload.scope ?? '',
  };
}

/** Trade the one-time `code` the callback carries for an access token and a refresh token. */
export async function exchangeCode({ config, code }) {
  const payload = await tokenRequest(config, {
    grant_type: 'authorization_code',
    code,
    redirect_uri: config.redirectUri,
  });
  return readTokens(payload);
}

/**
 * A fresh access token from the refresh token.
 *
 * Xero rotates refresh tokens: each response carries a *new* one that replaces the last, so the caller
 * must store what comes back. Keeping the old one after a successful refresh is a lockout waiting to
 * happen the moment the replacement is used.
 */
export async function refreshTokens({ config, refreshToken }) {
  const payload = await tokenRequest(config, {
    grant_type: 'refresh_token',
    refresh_token: refreshToken,
  });
  return readTokens(payload);
}

/**
 * Every Xero organisation this connection can see — the practice's book of clients.
 *
 * One connection is one organisation, which is one client the practice acts for. This is the list a
 * practice would otherwise retype into the board every January.
 */
export async function fetchConnections({ accessToken }) {
  const response = await fetch(XERO_CONNECTIONS_URL, {
    headers: { authorization: `Bearer ${accessToken}`, accept: 'application/json' },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new XeroError(`Xero refused the connections request (${response.status})`, {
      status: response.status,
      raw: payload,
    });
  }
  // Xero answers this endpoint with a bare JSON array; the defensive shape-read costs one line and
  // turns a silently-empty import into a clear refusal if that ever changes.
  return Array.isArray(payload) ? payload : (payload?.Connections ?? []);
}

/**
 * Connections into `{ name, email }` rows for the ingestion pipeline.
 *
 * The organisation's name is the client's name. Xero's `connections` carry no contact address, so the
 * email comes through blank — which the pipeline already handles as "a client the practice chases by
 * phone", counted and shown rather than dropped. This is the seam where a richer source (Practice
 * Manager's Clients, which carry contacts) is aimed at the same pipeline.
 */
export function connectionsToRows(connections) {
  return connections
    .map((connection) => ({ name: String(connection?.tenantName ?? '').trim(), email: '' }))
    .filter((row) => row.name !== '');
}

export const XERO_ORGANISATION_URL = 'https://api.xero.com/api.xro/2.0/Organisation';

/**
 * One organisation's filing profile — the facts that decide *what* to ask a client for and *when*.
 *
 * The import today reads the client list and throws the rest away, but the `accounting.settings` scope
 * the connection already carries reaches the Organisation record: the legal entity type, the financial
 * year end, and the tax registration. Those three facts are the difference between a generic checklist
 * and the right one at the right time — a limited company with a 31 March year end needs a different
 * January from a sole trader. Reading them is one call per client and needs no permission the practice
 * has not already granted, which is what makes this the first thing to build rather than a new feature.
 */
export async function fetchOrganisation({ accessToken, tenantId }) {
  const response = await fetch(XERO_ORGANISATION_URL, {
    headers: {
      authorization: `Bearer ${accessToken}`,
      accept: 'application/json',
      'xero-tenant-id': tenantId,
    },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new XeroError(`Xero refused the organisation request (${response.status})`, {
      status: response.status,
      raw: payload,
    });
  }
  // The endpoint answers `{ Organisations: [ one ] }`; a bare object is tolerated for the same
  // defensive reason `fetchConnections` tolerates a bare array.
  const organisations = Array.isArray(payload) ? payload : (payload?.Organisations ?? []);
  return organisations[0] ?? null;
}

/**
 * The raw Organisation record down to the handful of facts a request is built from.
 *
 * Deliberately only what decides the checklist and the date — a filing profile is not a mirror of the
 * accounting file, and everything here is a fact Xero states rather than one this code infers. The
 * month is what decides when to ask, so it is required; the day only refines it and may be absent
 * (some providers state a month alone). No month at all means no year end, because a wrong due date is
 * worse than no due date.
 */
export function organisationToProfile(organisation) {
  if (!organisation) return null;
  const day = Number(organisation.FinancialYearEndDay ?? 0);
  const month = Number(organisation.FinancialYearEndMonth ?? 0);
  const taxNumber = String(organisation.TaxNumber ?? '').trim();
  return {
    name: String(organisation.Name ?? organisation.LegalName ?? '').trim(),
    entityType: String(organisation.OrganisationType ?? '').trim() || null,
    yearEnd: month > 0 ? { day: day > 0 ? day : null, month } : null,
    taxNumber: taxNumber || null,
    baseCurrency: String(organisation.BaseCurrency ?? '').trim() || null,
    countryCode: String(organisation.CountryCode ?? '').trim() || null,
  };
}

/**
 * The client list with each organisation's filing profile attached to its row — the rows
 * `connectionsToRows` makes, plus the facts a request is built on. One Organisation read per client,
 * against a scope the connection already carries.
 *
 * One organisation is one client a practice acts for, so each row gets its own profile. A profile that
 * will not come back leaves its row without one rather than failing the import: the client list is the
 * point, and the filing profile is a refinement of it — one unreadable organisation is not a reason to
 * drop its client.
 */
export async function connectionsToRowsWithProfiles({ accessToken, connections }) {
  const rows = [];
  for (const connection of connections ?? []) {
    const name = String(connection?.tenantName ?? '').trim();
    if (!name) continue;
    let filingProfile = null;
    try {
      filingProfile = organisationToProfile(await fetchOrganisation({ accessToken, tenantId: connection.tenantId }));
    } catch {
      // One organisation that will not read is not a reason to drop its client.
    }
    rows.push({ name, email: '', filingProfile });
  }
  return rows;
}

export const XERO_BANKTRANSACTIONS_URL = 'https://api.xero.com/api.xro/2.0/BankTransactions';

/**
 * A summary of where a client's books stand — the one thing the "books behind" signal reads beyond the
 * client list, and the least it can read to answer "are they behind?".
 *
 * It reduces the bank transactions to a **count of the unreconciled ones and the date of the last one**,
 * and discards the transactions themselves: Tickmark keeps a number and a date, never a client's bank
 * lines. Read-only, and called only when the practice has turned the signal on — the connection never
 * carries this scope until then. See docs/security.md for the posture in full.
 */
export async function fetchBooksSignal({ accessToken, tenantId }) {
  const response = await fetch(XERO_BANKTRANSACTIONS_URL, {
    headers: {
      authorization: `Bearer ${accessToken}`,
      accept: 'application/json',
      'xero-tenant-id': tenantId,
    },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new XeroError(`Xero would not give up the books signal (${response.status})`, {
      status: response.status,
      raw: payload,
    });
  }
  const transactions = Array.isArray(payload) ? payload : (payload?.BankTransactions ?? []);
  // Reduce here and now: a count and a date go on from this function, and the rows go no further.
  let unreconciled = 0;
  let lastActivityAt = null;
  for (const transaction of transactions) {
    if (transaction.Reconciled === false) unreconciled += 1;
    const date = String(transaction.Date ?? '').slice(0, 10);
    if (date && (lastActivityAt === null || date > lastActivityAt)) lastActivityAt = date;
  }
  return { unreconciled, lastActivityAt };
}

/**
 * The books signal for each organisation a connection holds — one read per client, reduced to a summary
 * and no more. A signal that will not come back leaves that client out rather than failing the whole
 * check: the count and the date are a refinement, and the clients are the point.
 */
export async function booksSignalsForConnections({ accessToken, connections }) {
  const out = [];
  for (const connection of connections ?? []) {
    const name = String(connection?.tenantName ?? '').trim();
    if (!name) continue;
    let signal = null;
    try {
      signal = await fetchBooksSignal({ accessToken, tenantId: connection.tenantId });
    } catch {
      // one organisation that will not read is not a reason to stop the rest
    }
    out.push({ name, signal });
  }
  return out;
}

/**
 * Xero Practice Manager — the richer client record: a name *and* an email.
 *
 * ## The gate
 *
 * Xero keeps the Practice Manager API behind a partner gate: before the `practicemanager` scope is
 * granted at all, the developer passes a self-assessment against Xero's "Security standard for API
 * Consumers" and has the use case approved (api@support.xero.com) — and each user must flip "Connect
 * third-party add-ons" on in their XPM staff settings. So this half of the import is built and tested
 * here, and reaches a live practice only once Xero has approved the app. The `connections` half
 * (names) works today with no approval at all.
 *
 * ## What it reads
 *
 * A Practice Manager Client carries `Name`, its own `Email`, and `Contacts[]` each with an `Email` and
 * an `IsPrimary`. The client's own email wins; failing that the primary contact's; failing that any
 * contact's — because "the address to chase" is usually the person, not the company.
 */

// The exact path is the one thing that cannot be pinned down without a live XPM tenant to call; it is
// confirmed against the real API the first time an approved app connects. The shape below is not in
// doubt — it is Xero's own documented Client object.
export const XERO_PM_CLIENTS_URL = 'https://api.xero.com/practicemanager.xro/2.0/clients';

/** What a Practice Manager import asks for. `practicemanager` is the gated scope. */
export const XERO_PM_SCOPES = ['openid', 'email', 'profile', 'offline_access', 'practicemanager'].join(' ');

/**
 * The practice's Practice Manager client list — name *and* email, unlike `connections`.
 *
 * One `xero-tenant-id` is one Practice Manager tenant (a practice runs one). The list comes back under
 * `Clients`; a bare array is tolerated for the same reason `fetchConnections` tolerates one.
 */
export async function fetchPracticeManagerClients({ accessToken, tenantId }) {
  const response = await fetch(XERO_PM_CLIENTS_URL, {
    headers: {
      authorization: `Bearer ${accessToken}`,
      accept: 'application/json',
      'xero-tenant-id': tenantId,
    },
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new XeroError(`Xero Practice Manager refused the client list (${response.status})`, {
      status: response.status,
      raw: payload,
    });
  }
  return Array.isArray(payload) ? payload : (payload?.Clients ?? []);
}

/**
 * Practice Manager clients into `{ name, email }` rows — the same shape `connectionsToRows` produces,
 * so both pour into one ingestion pipeline.
 *
 * Email preference: the client's own `Email`, else the primary contact's, else any contact's. A client
 * with no email at all still comes through as a name — the pipeline counts those as "chased by phone"
 * rather than dropping them.
 */
export function practiceManagerClientsToRows(clients) {
  return (clients ?? [])
    .map((client) => {
      const name = String(client?.Name ?? '').trim();
      const contacts = Array.isArray(client?.Contacts) ? client.Contacts : [];
      const email =
        String(client?.Email ?? '').trim() ||
        String(contacts.find((contact) => contact?.IsPrimary)?.Email ?? '').trim() ||
        String(contacts.find((contact) => contact?.Email)?.Email ?? '').trim();
      return { name, email };
    })
    .filter((row) => row.name !== '');
}